[pytest]
testpaths = tests
addopts = --headed --html=reports/report.html --self-contained-html
markers =
    smoke: pruebas críticas rápidas
    regression: suite completa de pruebas
    negative: casos de error y validación